### ISSUE TITLE
How can I combine multiple properties?

### ISSUE THREAD

**Issue by expkzb** [sobri909/MGMushParser#3]
{#FFFFFF font:Arial,18pt | my text} is not working

**Comment by sobri909** [comment]
Wrap one inside the other. So something like this should work:

`{#FFFFFF|{font:Arial,18pt|my text}}`

**Comment by staminajim** [comment]
It might be cool to be able to stack properties using the pipe char so that they all squash to the right:
`{#FFFFFF|font:Arial,18p|k4.5t|my text}`

**Comment by sobri909** [comment]
@staminajim That sounds great! Looking forward to your commit ;)

**Comment by expkzb** [comment]
@sobri909 got it
