### ISSUE TITLE
Nested bold & italic bug

### ISSUE THREAD

**Issue by lewis-smith** [sobri909/MGMushParser#5]
I can't get a nested Mush working :(

     NSAttributedString *attributedText = [MGMushParser attributedStringFromMush:@"//**Half price** for a limited time//" font: _priceLabel.font color:[UIColor blackColor]];

Actual

_Half price for a limited time_

Expected

_**Half price** for a limited time_

Any help really appreciated, feel like I'm missing something very obvious.

**Comment by sobri909** [comment]
Hm. That should just work. Looks like something we would've used a million times...

Might be worth checking that the chosen font does have a bold version. Although seems like a long shot. But that's my first guess at what to check.

**Comment by sobri909** [comment]
Oh, the font have to have a bold+italics version, not just a bold version. Or rather, italics+boldWeight. Or however those lower level font metrics work. It's been years since I looked.

**Comment by lewis-smith** [comment]
Thanks for the reply :) 

The font did have a bold and italic version because I got it working with a regular attributed string.

But it's still possible* that I was making a mistake.

*likely
